import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {Button, Card, CardActionArea, CardActions, CardContent, CardMedia, Typography} from "@mui/material";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>پرسشنامه</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div align="center" dir="rtl">
                <Card sx={{maxWidth: 500}}>
                    <CardActionArea>
                        <CardMedia
                            component="img"
                            height="400"
                            image="/img.png"
                            alt="green iguana"
                        />
                        <CardContent>
                            <Typography gutterBottom variant="h5" component="div">
                                پرسشنامه
                            </Typography>
                            <Typography variant="body2" color="text.secondary">
                                با سلام خدمت استاد عزیز خوش آمدید.
                            </Typography>
                        </CardContent>
                    </CardActionArea>
                    <div align="center">
                        <CardActions>
                            <Link href="/steps/1">
                                <a>
                                    <Button variant="outlined" color="primary">
                                        شروع
                                    </Button>
                                </a>
                            </Link>
                        </CardActions></div>
                </Card>
            </div>
        </div>
    )
}
